@startuml vista-interaccion
skinparam sequenceParticipant underline
skinparam roundcorner 30

actor ":EncargadoDeBolsines" as EB
boundary ":PantallaAdminBolsin" as pantalla
control ":GestorAdminBolsin" as gestor
entity "activa:Sesion" as Sesion
entity "logueado:Usuario" as Logueado
entity ":Empleado" as Empleado #OrangeRed
entity "logueado:Empleado" as LogEmp 
entity ":Bolsin" as Bolsin #OrangeRed
entity "deEmp:ComisionMedica" as CMEmp
entity "deBolsin:ComisionMedica" as CMBolsin
entity ":CambioEstadoBolsin" as CambioEstadoBolsin #OrangeRed
entity "actual:CambioEstadoBolsin" as cambioEstadoActual
entity "nuevo:CambioEstadoBolsin" as nuevoCambioEstado
entity "delCambioEstado:Estado" as estadoActual
entity ":Estado" as Estado #OrangeRed
entity "seleccionado:Bolsin" as bolsinSeleccionado
entity "actual:CambioEstadoDocumentacion" as estadoActualDocumentacion
entity ":cambioEstadoDocumentacion" as CEDoc #OrangeRed
entity "nuevo:CambioEstadoDocumentacion" as nuevoEstadoDocumentacion
entity "seleccionado:Remito" as remitoSeleccionado
entity "seleccionado:DetalleRemito" as detalleRemitoSeleccionado
entity "seleccionado:Documentacion" as documentacionSeleccionada
entity "deDocumentacion:TipoDocumentacion" as TipoDocumentacion
participant "29 Notificar Recepción de Bolsin" as casoDeUso29 #8cbce4


'"29. Notificar Recepción de Bolsin"

EB --> pantalla ** : opcionRegRecepBolsin()
pantalla -> pantalla : habilitarPantalla()
pantalla --> gestor ** : regRecepBolsin()
gestor -> gestor : getUsuarioLogueado()
gestor -> Sesion : getUsuarioLogueado()
Sesion -> Logueado : getUsuario()
gestor -> Empleado : //*//esTuUsuario()
gestor -> gestor : getCMEmpleado()
gestor -> LogEmp : getCM()
LogEmp -> CMEmp : getNombre()
gestor -> pantalla : mostrarCMEmpleado()

gestor -> gestor : getBolsinesEnviados()
loop Mientras haya bolsines
    gestor -> Bolsin : esTuCMdestino()
    gestor -> Bolsin : esEnviado()
'   Bolsin -> Bolsin : obtenerEstadoActual()
    Bolsin -> CambioEstadoBolsin : //*//esEstadoActual()
    Bolsin -> cambioEstadoActual : sosEnviado()
    'cambioEstadoActual -> estadoActual : esAmbitoBolsin()
    'Hace falta preguntar ámbito si es el estado apuntado por cambioEstado?
    cambioEstadoActual -> estadoActual : sosEnviado()
    gestor -> Bolsin : getCMOrigen()
    Bolsin -> CMBolsin : getNombre()
    gestor -> Bolsin : getNroPrecinto()
end

gestor -> pantalla : mostrarDatosBolsinesEnviados()
EB -> pantalla : tomarSelecBolsin()
pantalla -> gestor : tomarSelecBolsin()
gestor -> gestor : getRemitosAsociados()
gestor -> bolsinSeleccionado : obtenerInformacionRemito()
loop Mientras haya remitos asociados al Bolsin
    bolsinSeleccionado -> remitoSeleccionado : getNumero()
    bolsinSeleccionado -> remitoSeleccionado : buscarDocumentacion()
    loop Mientras haya DetalleRemitos
        remitoSeleccionado -> detalleRemitoSeleccionado : getDocumentacion()
        detalleRemitoSeleccionado -> documentacionSeleccionada : getAsunto()
        detalleRemitoSeleccionado -> documentacionSeleccionada : getTipoDocumentacion()
        documentacionSeleccionada -> TipoDocumentacion : getNombre()
    end
end

gestor -> pantalla : mostrarDatosRemitoyDoc()
gestor -> pantalla : solicitarOpcionRecepBolsin()
EB -> pantalla : tomarOpcionContenidoOK()
pantalla -> gestor : tomarOpcionContenidoOK()
gestor -> pantalla : solicitarConfirmacion()
EB -> pantalla : tomarConfirmacion()
pantalla -> gestor : tomarConfirmacion()

'Actualizacion de estados

gestor -> gestor : buscarEstadosAAsignar()
loop Mientras haya estados
    gestor -> Estado :  esAmbitoBolsin()
    gestor -> Estado : esRecibido()
    gestor -> Estado : es AmbitoRemito()
    gestor -> Estado : es RecibidoYAceptado()
    gestor -> Estado : es AmbitoDocumentacion()
    gestor -> Estado : es RecibidaYAceptada()
end
gestor -> gestor : getFechaYHoraActual()
'gestor -> gestor : getUsuarioLogeado() lo hice más arriba
gestor -> gestor : recibirBolsin()
gestor -> bolsinSeleccionado : recibir()
bolsinSeleccionado -> bolsinSeleccionado : getEstadoActual()
bolsinSeleccionado -> cambioEstadoActual : setFechaHoraFin()
bolsinSeleccionado -> bolsinSeleccionado : crearCEBolsin()
bolsinSeleccionado --> nuevoCambioEstado ** : new()

bolsinSeleccionado -> bolsinSeleccionado : recibirAceptarRemito()

loop Para todos los remitos asociados al bolsín seleccionado
    bolsinSeleccionado -> remitoSeleccionado : recibirAceptar()
    remitoSeleccionado -> remitoSeleccionado : setEstado()
    remitoSeleccionado -> remitoSeleccionado : actualizarEstadoDoc()
    
    loop Recorrer detalleRemito
        remitoSeleccionado -> detalleRemitoSeleccionado : actualizarEstadoDoc()
        detalleRemitoSeleccionado -> documentacionSeleccionada : actualizarEstadoDoc()
        documentacionSeleccionada -> documentacionSeleccionada : getEstadoActual()
        documentacionSeleccionada -> CEDoc : //*//sosActual()
        documentacionSeleccionada -> estadoActualDocumentacion : setFechaHoraFin()
        documentacionSeleccionada -> documentacionSeleccionada : crearCambioEstadoDocumentacion()
        documentacionSeleccionada --> nuevoEstadoDocumentacion ** : new()

    end
end
gestor -> casoDeUso29 : <<include>>
gestor -> pantalla : informarEjecucionExitosa()
gestor -> gestor : finCU()









hide footbox
@enduml
