@startuml vista-analisis

class Empleado <<entity>> {
  apellido
  nombre
  getCM()
  esTuUsuario()
}

class Usuario <<entity>> {
  nombre
  password
}

class Sesion <<entity>> {
  fechaHoraInicio
  fechaHoraFin
  getUsuario()
}

class GestorRegRecepBolsin <<control>> {
  cmEmpleado
  bolsinesEnviados
  bolsinSeleccionado
  opcionRecepcionSeleccionada
  confirmado
  regRecepBolsin()
  getCMEmpleado()
  getBolsinesEnviados()
  tomarSelecBolsin()
  getRemitosAsociados()
  tomarConfirmacion()
  tomarOpcionContenidoOK()
  buscarEstadosAAsignar()
  getFechaYHoraActual()
  confirmarRecepcion()
  llamarCUNotifRecepBolsin()
  finCU()
}

class PantallaRegRecepBolsin <<boundary>> {
  txtCMEmpleado
  cmbBolsinesEnviados
  inputFiltroPrecinto
  cmbOpcionesRecepcion
  btnConfirmar
  habilitarPantalla()
  opcionRegRecepBolsin()
  tomarSelecBolsin()
  solicitarConfirmacion()
  tomarConfirmacion()
  mostrarCMEmpleado()
  mostrarDatosBolsinesEnviados()
  mostrarDatosRemitoyDoc()
  solicitarOpcionRecepBolsin()
  tomarOpcionContenidoOK()
  informarEjecucionExitosa()
}

class ComisionMedica <<entity>> {
  codigo
  direccion
  email
  nombre
  telefono
  getNombre()
}

class Bolsin <<entity>> {
  fecha
  numeroBolsin
  numeroPrecinto
  peso
  asociarRemito()
  crearCEBolsin()
  setEstado()
  tenesEstaCMDestino()
  esEnviado()
  getNroPrecinto()
  getNumeroBolsin()
  new()
  obtenerEstadoActual()
  obtenerInformacionRemito()
  setDetalleBolsin()
  getCMOrigen()
  recibir()
  recibirAceptarRemito()
}

class CambioEstadoBolsin <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  esActual()
  new()
  setEstado()
  setFechaHoraFin()
  setResponsableCE()
  sosEnviado()
}

class Estado <<entity>> {
  ambito
  descripcion
  nombre
  esAmbitoBolsin()
  esAmbitoDocumentacion()
  esAmbitoRemito()
  esEnviado()
  esRecibidaYAceptada()
  esRecibidoYAceptado()
  getAmbito()
  getDescripcion()
  getNombre()
  new()
  setAmbito()
  setDescripcion()
  setNombre()
  esRecibido()
}

class Remito <<entity>> {
  fecha
  número
  aceptarDocumentacion()
  buscarDocumentacion()
  estasGenerado()
  getDatosRemito()
  getNumero()
  new()
  setEstado()
  tenesEstaCMDestino()
  tenesEstaCMOrigen()
  tomarDocumentacion()
  recibirAceptar()
}

class DetalleRemito <<entity>> {
  areaCMCDestino
  aceptarDocumentacion()
  getDocumentacion()
}

class Documentacion <<entity>> {
  asunto
  fechaPase
  numero
  aceptar()
  agregarARemito()
  asociarBolsin()
  cancelar()
  crearCEDocumentacion()
  darDeBaja()
  desasociarBolsin()
  enviar()
  getNumero()
  getDatosDocumentacion()
  new()
  noRecibir()
  quitarDeRemito()
  rechazar()
  redirigir()
  remitar()
  setEstado()
  getEstadoActual()
  getTipoDocumento()
  registrar()
}

class CambioEstadoDocumentacion <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  new()
  setEstado()
  setFechaHoraFin()
  setResponsableCE()
  sosActual()
}

class TipoDocumento <<entity>> {
  descripcion
  nombre
  getDescripcion()
  getNombre()
  new()
  setDescripcion()
  setNombre()
}

PantallaRegRecepBolsin ..> GestorRegRecepBolsin
PantallaRegRecepBolsin <.. GestorRegRecepBolsin
GestorRegRecepBolsin ..> Sesion
GestorRegRecepBolsin ..> Empleado
GestorRegRecepBolsin ..> Bolsin
GestorRegRecepBolsin ..> Estado
Sesion "*" --> "1" Usuario : usuario
Empleado "1" --> "1" Usuario : usuario
Empleado "1" --> "1" ComisionMedica : asignadoA
Bolsin "*" --> "1" ComisionMedica : origen
Bolsin "*" --> "1" ComisionMedica : destino
Remito "*" --> "1" ComisionMedica : origen
Remito "*" --> "1" ComisionMedica : destino
Bolsin "1" --> "1..*" CambioEstadoBolsin : cambioEstado
CambioEstadoBolsin "*" --> "1" Estado : estado
Bolsin "1..*" o-> "1" Remito : remito
Remito "*" --> "1" Estado : estado
Remito "1" o-> "1..*" DetalleRemito : detalleRemito
DetalleRemito "*" --> "1" Documentacion : documentacion
Documentacion "*" --> "1" TipoDocumento : tipoDocumento
Documentacion "1" --> "1..*" CambioEstadoDocumentacion : cambioEstado
CambioEstadoDocumentacion "*" --> "1" Estado : estado

@enduml
