@startuml Realización de Análisis del CU 28 Registrar recepción de Bolsín - Vista Estática 

class Empleado <<entity>> {
  apellido
  nombre
  getCM()
  esTuUsuario()
}

class Usuario <<entity>> {
  nombre
  password
}

class Sesion <<entity>> {
  fechaHoraInicio
  fechaHoraFin
  getUsuario()
}

class GestorRegRecepBolsin <<control>> {
  cmEmpleado
  bolsinesEnviados
  bolsinSeleccionado
  opcionRecepcionSeleccionada
  confirmado
  regRecepBolsin()
  getCMEmpleado()
  getBolsinesEnviados()
  buscarDatosBolsin()
  tomarSelecBolsin()
  getRemitosAsociados()
  getDocumentacionAsociada()
  tomarConfirmacion()
  tomarOpcionContenidoOK()
  buscarEstadoRecibido()
  buscarEstadoRecibidaYAceptada()
  buscarEstadoRecibidoYAceptado()
  getFechaYHoraActual()
  confirmarRecepcion()
  llamarCUNotifRecepBolsin()
  finCU()
}

class PantallaRegRecepBolsin <<boundary>> {
  txtCMEmpleado
  cmbBolsinesEnviados
  inputFiltroPrecinto
  cmbOpcionesRecepcion
  btnConfirmar
  habilitarPantalla()
  opcionRegRecepBolsin()
  habilitarOpcSelección()
  tomarSelecBolsin()
  solicitarConfirmacion()
  tomarConfirmacion()
  mostrarCMEmpleado()
  mostrarDatosBolsinesEnviados()
  mostrarDatosRemitoyDoc()
  solicitarOpcionRecepBolsin()
  tomarOpcionContenidoOK()
  informarEjecucionExitosa()
}

class ComisionMedica <<entity>> {
  codigo
  direccion
  email
  nombre
  telefono
  getNombre()
}

class Bolsin <<entity>> {
  fecha
  numeroBolsin
  numeroPrecinto
  peso
  asociarRemito()
  crearCEBolsin()
  tenesEstaCMDestino()
  sosEnviado()
  getNroPrecinto()
  getNumeroBolsin()
  new()
  obtenerEstadoActual()
  obtenerInformacionRemito()
  setDetalleBolsin()
  getCMOrigen()
  recibir()
  recibirAceptarRemito()
}

class CambioEstadoBolsin <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  esActual()
  new()
  setFechaHoraFin()
  sosEnviado()
}

class Estado <<entity>> {
  ambito
  descripcion
  nombre
  esAmbitoBolsin()
  esAmbitoDocumentacion()
  esAmbitoRemito()
  esEnviado()
  esRecibidaYAceptada()
  esRecibidoYAceptado()
  getAmbito()
  getDescripcion()
  getNombre()
  new()
  setAmbito()
  setDescripcion()
  setNombre()
  esRecibido()
}

class Remito <<entity>> {
  fecha
  número
  aceptarDocumentacion()
  buscarDocumentacion()
  estasGenerado()
  getDatosRemito()
  getNumero()
  new()
  setEstado()
  tenesEstaCMDestino()
  tenesEstaCMOrigen()
  tomarDocumentacion()
  recibirAceptar()
}

class DetalleRemito <<entity>> {
  areaCMCDestino
  aceptarDocumentacion()
  getDocumentacion()
}

class Documentacion <<entity>> {
  asunto
  fechaPase
  numero
  aceptar()
  agregarARemito()
  asociarBolsin()
  cancelar()
  crearCEDocumentacion()
  darDeBaja()
  desasociarBolsin()
  enviar()
  getAsunto()
  new()
  noRecibir()
  quitarDeRemito()
  rechazar()
  redirigir()
  remitar()
  setEstado()
  getEstadoActual()
  getTipoDocumento()
  registrar()
}

class CambioEstadoDocumentacion <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  new()
  setFechaHoraFin()
  sosActual()
}

class TipoDocumento <<entity>> {
  descripcion
  nombre
  getDescripcion()
  getNombre()
  new()
  setDescripcion()
  setNombre()
}

PantallaRegRecepBolsin ..> GestorRegRecepBolsin
PantallaRegRecepBolsin <.right. GestorRegRecepBolsin
GestorRegRecepBolsin ..> Sesion
GestorRegRecepBolsin ..> Empleado
GestorRegRecepBolsin ..> Bolsin
GestorRegRecepBolsin ..> Estado
Sesion --> "1" Usuario : usuario
Empleado --> "0..1" Usuario : usuario
Empleado "asignadoA" --> "1" ComisionMedica
Bolsin --> "1" ComisionMedica : origen
Bolsin --> "1" ComisionMedica : destino
Remito --> "1" ComisionMedica : origen
Remito --> "1" ComisionMedica : destino
Bolsin --> "1..*" CambioEstadoBolsin : cambioEstado
CambioEstadoBolsin "estado" --> "1" Estado
Bolsin o-> "1..*" Remito : remito
Remito --> "1" Estado : estado
Remito o-> "1..*" DetalleRemito : detalleRemito
DetalleRemito -right-> "1" Documentacion : documentacion
Documentacion --> "1" TipoDocumento : tipoDocumento
Documentacion --> "1..*" CambioEstadoDocumentacion : cambioEstado
CambioEstadoDocumentacion --> "1" Estado : estado

@enduml
