@startuml vista-interaccion
skinparam sequenceParticipant underline
skinparam roundcorner 30

actor ":EncargadoDeBolsines" as EB
boundary ":PantallaRegRecepBolsin" as pantalla
control ":GestorRegRecepBolsin" as gestor
entity "activa:Sesion" as Sesion
entity ":Empleado" as Empleado #OrangeRed
entity "logueado:Empleado" as LogEmp 
entity ":Bolsin" as Bolsin #OrangeRed
entity "actual:ComisionMedica" as CMEmp
entity "actual:ComisionMedica" as CMBolsin
entity ":CambioEstadoBolsin" as CambioEstadoBolsin #OrangeRed
entity "actual:CambioEstadoBolsin" as cambioEstadoActual
entity "nuevo:CambioEstadoBolsin" as nuevoCambioEstado
entity "actual:Estado" as estadoActual
entity ":Estado" as Estado #OrangeRed
entity "seleccionado:Bolsin" as bolsinSeleccionado
entity "actual:CambioEstadoDocumentacion" as estadoActualDocumentacion
entity ":CambioEstadoDocumentacion" as CEDoc #OrangeRed
entity "nuevo:CambioEstadoDocumentacion" as nuevoEstadoDocumentacion
entity "seleccionado:Remito" as remitoSeleccionado
entity "seleccionado:DetalleRemito" as detalleRemitoSeleccionado
entity "seleccionado:Documentacion" as documentacionSeleccionada
entity "actual:TipoDocumento" as TipoDocumento
participant "29 Notificar Recepción de Bolsin" as casoDeUso29 #8cbce4


'"29. Notificar Recepción de Bolsin"

EB --> pantalla ** : opcionRegRecepBolsin()
pantalla -> pantalla : habilitarPantalla()
pantalla --> gestor ** : regRecepBolsin()
gestor -> Sesion : getUsuario()
gestor -> Empleado : //*//esTuUsuario()
gestor -> gestor : getCMEmpleado()
gestor -> LogEmp : getCM()
LogEmp -> CMEmp : getNombre()

gestor -> gestor : getBolsinesEnviados()
gestor -> Bolsin : //*//tenesEstaCMDestino()
loop Mientras hayan bolsines asociados a CM Destino
    gestor -> Bolsin : esEnviado()
    Bolsin -> CambioEstadoBolsin : //*//esActual()
    Bolsin -> cambioEstadoActual : sosEnviado()
    cambioEstadoActual -> estadoActual : esEnviado()
end
loop Mientras hayan bolsines enviados asociados a CM Destino
    gestor -> Bolsin : getNroPrecinto()
    gestor -> Bolsin : getCMOrigen()
    Bolsin -> CMBolsin : getNombre()
end

gestor -> pantalla : mostrarCMEmpleado()
gestor -> pantalla : mostrarDatosBolsinesEnviados()
EB -> pantalla : tomarSelecBolsin()
pantalla -> gestor : tomarSelecBolsin()
gestor -> gestor : getRemitosAsociados()
gestor -> bolsinSeleccionado : obtenerInformacionRemito()
loop Mientras haya remitos asociados al Bolsin
    bolsinSeleccionado -> remitoSeleccionado : getNumero()
    bolsinSeleccionado -> remitoSeleccionado : buscarDocumentacion()
    loop Mientras haya DetalleRemitos
        remitoSeleccionado -> detalleRemitoSeleccionado : getDocumentacion()
        detalleRemitoSeleccionado -> documentacionSeleccionada : getDatosDocumentacion()
        documentacionSeleccionada -> documentacionSeleccionada : getNumero()
        documentacionSeleccionada -> documentacionSeleccionada : getTipoDocumento()
        documentacionSeleccionada -> TipoDocumento : getNombre()
    end
end

gestor -> pantalla : mostrarDatosRemitoyDoc()
gestor -> pantalla : solicitarOpcionRecepBolsin()
EB -> pantalla : tomarOpcionContenidoOK()
pantalla -> gestor : tomarOpcionContenidoOK()
gestor -> pantalla : solicitarConfirmacion()
EB -> pantalla : tomarConfirmacion()
pantalla -> gestor : tomarConfirmacion()

'Actualizacion de estados

gestor -> gestor : getFechaYHoraActual()
'gestor -> Sesion : getUsuario() lo hice más arriba
gestor -> gestor : confirmarRecepcion()
gestor -> bolsinSeleccionado : recibir()
bolsinSeleccionado -> bolsinSeleccionado : obtenerEstadoActual()
bolsinSeleccionado -> cambioEstadoActual : setFechaHoraFin()
bolsinSeleccionado -> Estado : //*//esAmbitoBolsin()
bolsinSeleccionado -> Estado : //*//esRecibido()
bolsinSeleccionado -> bolsinSeleccionado : crearCEBolsin()
bolsinSeleccionado --> nuevoCambioEstado ** : new()
nuevoCambioEstado -> nuevoCambioEstado : setEstado()
nuevoCambioEstado -> nuevoCambioEstado : setResponsableCE()
bolsinSeleccionado -> bolsinSeleccionado : setEstado()

bolsinSeleccionado -> bolsinSeleccionado : recibirAceptarRemito()

loop Para todos los remitos asociados al bolsín seleccionado
    bolsinSeleccionado -> remitoSeleccionado : recibirAceptar()
    remitoSeleccionado -> Estado : //*//esAmbitoRemito()
    remitoSeleccionado -> Estado : //*//esRecibidoYAceptado()
    remitoSeleccionado -> remitoSeleccionado : setEstado()
    remitoSeleccionado -> remitoSeleccionado : aceptarDocumentacion()
    
    loop Recorrer detalleRemito
        remitoSeleccionado -> detalleRemitoSeleccionado : aceptarDocumentacion()
        detalleRemitoSeleccionado -> documentacionSeleccionada : aceptar()
        documentacionSeleccionada -> documentacionSeleccionada : getEstadoActual()
        documentacionSeleccionada -> CEDoc : //*//sosActual()
        documentacionSeleccionada -> estadoActualDocumentacion : setFechaHoraFin()
        documentacionSeleccionada -> Estado : //*//esAmbitoDocumentacion()
        documentacionSeleccionada -> Estado : //*//esRecibidaYAceptada()
        documentacionSeleccionada -> documentacionSeleccionada : crearCEDocumentacion()
        documentacionSeleccionada --> nuevoEstadoDocumentacion ** : new()
        nuevoEstadoDocumentacion -> nuevoEstadoDocumentacion : setEstado()
        nuevoEstadoDocumentacion -> nuevoEstadoDocumentacion : setResponsableCE()
        documentacionSeleccionada -> documentacionSeleccionada : setEstado()
    end
end
gestor -> gestor : llamarCUNotifRecepBolsin()
gestor -> casoDeUso29 : <<include>>
gestor -> pantalla : informarEjecucionExitosa()
gestor -> gestor : finCU()









hide footbox
@enduml
