@startuml Realización de Análisis del CU 28 Registrar recepción de Bolsín - Vista Dinámica

skinparam participant<<rd>> {
    RoundCorner 30
    BackgroundColor #8cbce4
}

hide stereotype

actor "<u>:EncargadoDeBolsines</u>" as EB
boundary "<u>:PantallaRegRecepBolsin</u>" as pantalla
control "<u>:GestorRegRecepBolsin</u>" as gestor
entity "<u>activa:Sesion</u>" as Sesion
entity "<u>:Empleado</u>" as Empleado #OrangeRed
entity "<u>logueado:Empleado</u>" as LogEmp 
entity "<u>:Bolsin</u>" as Bolsin #OrangeRed
entity "<u>actual:ComisionMedica</u>" as CMEmp
entity "<u>actual:ComisionMedica</u>" as CMBolsin
entity "<u>:CambioEstadoBolsin</u>" as CambioEstadoBolsin #OrangeRed
entity "<u>actual:CambioEstadoBolsin</u>" as cambioEstadoActual
entity "<u>nuevo:CambioEstadoBolsin</u>" as nuevoCambioEstado
entity "<u>actual:Estado</u>" as estadoActual
entity "<u>:Estado</u>" as Estado #OrangeRed
entity "<u>:Remito</u>" as Remito #OrangeRed
entity "<u>:DetalleRemito</u>" as DetalleRemito #OrangeRed
entity "<u>seleccionado:Bolsin</u>" as bolsinSeleccionado
entity "<u>actual:CambioEstadoDocumentacion</u>" as estadoActualDocumentacion
entity "<u>:CambioEstadoDocumentacion</u>" as CEDoc #OrangeRed
entity "<u>nuevo:CambioEstadoDocumentacion</u>" as nuevoEstadoDocumentacion
entity "<u>actual:Documentacion</u>" as documentacionSeleccionada
entity "<u>actual:TipoDocumento</u>" as TipoDocumento
Participant "29 Notificar Recepción de Bolsin" as casoDeUso29 <<rd>>


'"29. Notificar Recepción de Bolsin"

EB --> pantalla ** : opcionRegRecepBolsin()
pantalla -> pantalla : habilitarPantalla()
pantalla --> gestor ** : regRecepBolsin()
gestor -> Sesion : getUsuario()
gestor -> Empleado : //*//esTuUsuario()
gestor -> gestor : getCMEmpleado()
gestor -> LogEmp : getCM()
LogEmp -> CMEmp : getNombre()
gestor -> pantalla : mostrarCMEmpleado()
gestor -> gestor : getBolsinesEnviados()

group loop buscar bolsines enviados[Mientras hayan bolsines asociados a CM Destino]
    gestor -> Bolsin : tenesEstaCMDestino()
    gestor -> Bolsin : sosEnviado()
    group loop para todos los bolsines de CM[Mientras haya bolsines]
        Bolsin -> CambioEstadoBolsin : //*//esActual()
        Bolsin -> cambioEstadoActual : sosEnviado()
        cambioEstadoActual -> estadoActual : esEnviado()
    end

gestor -> gestor : buscarDatosBolsin()

    gestor -> Bolsin : getNroPrecinto()
    gestor -> Bolsin : getCMOrigen()
    Bolsin -> CMBolsin : getNombre()
end

gestor -> pantalla : mostrarDatosBolsinesEnviados()
gestor -> pantalla : habilitarOpcSelección()
EB -> pantalla : tomarSelecBolsin()
pantalla -> gestor : tomarSelecBolsin()
gestor -> gestor : getRemitosAsociados()
gestor -> gestor : getDocumentacionAsociada()
gestor -> bolsinSeleccionado : obtenerInformacionRemito()
loop Mientras hayan remitos asociados al Bolsin Seleccionado
    bolsinSeleccionado -> Remito : getNumero()
    bolsinSeleccionado -> Remito : buscarDocumentacion()
    loop Mientras hayan DetalleRemitos asociados
        Remito -> DetalleRemito : getDocumentacion()
        DetalleRemito -> documentacionSeleccionada : getAsunto()
        DetalleRemito -> documentacionSeleccionada : getTipoDocumento()
        documentacionSeleccionada -> TipoDocumento : getNombre()
    end
end

gestor -> pantalla : mostrarDatosRemitoyDoc()
gestor -> pantalla : solicitarOpcionRecepBolsin()
EB -> pantalla : tomarOpcionContenidoOK()
pantalla -> gestor : tomarOpcionContenidoOK()
gestor -> pantalla : solicitarConfirmacion()
EB -> pantalla : tomarConfirmacion()
pantalla -> gestor : tomarConfirmacion()

'Actualizacion de estados
gestor -> gestor : getFechaYHoraActual()
gestor -> gestor : buscarEstadoRecibido()
' Buscar estado Recibido en CM destino para Bolsin

group loop estados para Bolsin[Mientras haya estados]
    gestor -> Estado : esAmbitoBolsin()
    gestor -> Estado : esRecibido()
end

gestor -> gestor : buscarEstadoRecibidoYAceptado()
' Buscar estado Recibido y Aceptado para Remito
group loop estados para remito[Mientras haya estados]
    gestor -> Estado : esAmbitoRemito()
    gestor -> Estado : esRecibidoYAceptado()
end
gestor -> gestor : buscarEstadoRecibidaYAceptada()
' Buscar estado Recibida y Aceptada para Documentacion
group loop estados para documentación[Mientras haya estados]
    gestor -> Estado : esAmbitoDocumentacion()
    gestor -> Estado : esRecibidaYAceptada()
end


'gestor -> Sesion : getUsuario() lo hice más arriba
gestor -> gestor : confirmarRecepcion()
gestor -> bolsinSeleccionado : recibir()
bolsinSeleccionado -> bolsinSeleccionado : obtenerEstadoActual()
bolsinSeleccionado -> cambioEstadoActual : setFechaHoraFin()
bolsinSeleccionado -> bolsinSeleccionado : crearCEBolsin()
bolsinSeleccionado --> nuevoCambioEstado ** : new()

bolsinSeleccionado -> bolsinSeleccionado : recibirAceptarRemito()

loop Mientras hayan remitos asociados al bolsín seleccionado
    bolsinSeleccionado -> Remito : recibirAceptar()
    Remito -> Remito : setEstado()
    Remito -> Remito : aceptarDocumentacion()
    
    loop Mientras hayan DetalleRemitos asociados al Remito
        Remito -> DetalleRemito : aceptarDocumentacion()
        DetalleRemito -> documentacionSeleccionada : aceptar()
        documentacionSeleccionada -> documentacionSeleccionada : getEstadoActual()
        documentacionSeleccionada -> CEDoc : //*//sosActual()
        documentacionSeleccionada -> estadoActualDocumentacion : setFechaHoraFin()
        documentacionSeleccionada -> documentacionSeleccionada : crearCEDocumentacion()
        documentacionSeleccionada --> nuevoEstadoDocumentacion ** : new()
        
    end
end
gestor -> gestor : llamarCUNotifRecepBolsin()
gestor -> casoDeUso29 : <<include>>
gestor -> pantalla : informarEjecucionExitosa()
gestor -> gestor : finCU()









hide footbox
@enduml
