@startuml Modelo de Dominio - Bolsines

skinparam classAttributeIconSize 0
skinparam stereotypeCBackgroundColor LightBlue
skinparam classBorderColor DarkBlue
skinparam classBackgroundColor White
skinparam arrowColor DarkBlue

' ========================
' ENTITIES
' ========================

class Provincia <<entity>> {
  descripcion
  nombre
}

class Localidad <<entity>> {
  descripcion
  nombre
}

class Empleado <<entity>> {
  apellido
  nombre
  getCM()
}

class TipoDocumento <<entity>> {
  descripcion
  nombre
  getDescripcion()
  getNombre()
  new()
  setDescripcion()
  setNombre()
}

class Archivo <<entity>> {
  nombreArchivo
  tituloDocumento
}

class ComisionMedica <<entity>> {
  codigo
  direccion
  email
  nombre
  telefono
  getNombre()
}

class DetalleRemito <<entity>> {
  areaCMCDestino
  actualizarEstadoDoc()
  getDocumentacion()
}

class Documentacion <<entity>> {
  asunto
  fechaPase
  numero
  aceptar()
  getDatosDocumentacion()
  new()
  remitar()
  setEstado()
}

class Bolsin <<entity>> {
  fecha
  numeroBolsin
  numeroPrecinto
  peso
  asociarRemito()
  crearCEBolsin()
  getNumeroBolsin()
  new()
  setDetalleBolsin()
}

class Remito <<entity>> {
  fecha
  número
  actualizarEstadoDoc()
  buscarDocumentacion()
  estasGenerado()
  getDatosRemito()
  modificarDocumentacionIncluida()
  new()
  setEstado()
  tenesEstaCMDestino()
  tenesEstaCMOrigen()
  tomarDocumentacion()
}

class Estado <<entity>> {
  ambito
  descripcion
  nombre
  esAmbitoBolsin()
  esAmbitoDocumentacion()
  esAmbitoRemito()
  getAmbito()
  getDescripcion()
  getNombre()
  new()
  setAmbito()
  setDescripcion()
  setNombre()
}

class CambioEstadoDocumentacion <<entity>> {
  fechaHoraFin
  fechaHoraInicio
}

class CambioEstadoBolsin <<entity>> {
  fechaHoraFin
  fechaHoraInicio
}

' ========================
' RELATIONSHIPS
' ========================

Localidad --> "1" Provincia : provincia
ComisionMedica --> "1" Localidad : localidad
Empleado --> "1" ComisionMedica : asignadoA

Documentacion --> "1" TipoDocumento : tipoDocumento
Documentacion "1..*" --> "*" Archivo : archivoAdjunto
Documentacion --> "1" ComisionMedica : cmOrigen
Documentacion --> "1..*" CambioEstadoDocumentacion : cambioEstado
CambioEstadoDocumentacion --> "1" Estado : estado
CambioEstadoDocumentacion --> "1" Empleado : responsableCE

DetalleRemito --> "1" Documentacion : documentacion
Remito "1" o--> "1..*" DetalleRemito : detalleRemito
Bolsin "1..*" o--> "1" Remito : remito

Bolsin --> "1" ComisionMedica : origen
Bolsin --> "1" ComisionMedica : destino
Remito --> "1" ComisionMedica : origen
Remito --> "1" ComisionMedica : destino

Bolsin --> "1..*" CambioEstadoBolsin : cambioEstado
CambioEstadoBolsin --> "1" Estado : estado
CambioEstadoBolsin --> "1" Empleado : responsableCE

@enduml
